# Generated by Django 2.1.3 on 2018-12-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_auto_20181204_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='progress_made',
            field=models.CharField(choices=[('incomplete', 'incomplete'), ('complete', 'complete'), ('inprogress', 'inprogress')], default='incomplete', max_length=2),
        ),
    ]
