# Generated by Django 2.1.3 on 2018-12-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0008_auto_20181204_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='progress_made',
        ),
        migrations.AddField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('incomplete', 'incomplete'), ('complete', 'complete')], default='incomplete', max_length=10),
        ),
    ]
