# Generated by Django 2.1.3 on 2018-12-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0009_auto_20181204_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='status',
        ),
        migrations.AddField(
            model_name='topic',
            name='priority',
            field=models.CharField(choices=[('high', 'high'), ('medium', 'medium'), ('low', 'low')], default='medium', max_length=6),
        ),
    ]
